config/routes.rb
WwwStudentpeaceprizeOrg::Application.routes.draw do

  scope "/:locale(/:tab)" do
    resources :pages

    resources :articles do
      collection do
        get :index_rest
        get :all
      end
    end
  end

  root :to => "articles#index", :tab => 'home'
  match '/:locale' => 'articles#index', :tab => 'home'
  match ':tab(/:controller(/:action(:id)))', :id => /.*/
end

app/models/article.rb
class Article < ActiveRecord::Base
  self.primary_key = :id

  scope :visible, where(deleted: 0, visible: 1)
  scope :sorted, order("weight DESC")
  scope :norwegian, where("title_no IS NOT ''")
  scope :english, where("title_en IS NOT ''")

  has_attached_file :spp_article_image, styles: {
      front_large: {geometry: "620x365#", processors: [:cropper]},
      front_small: {geometry: "220x131#", processors: [:cropper_half]},
      article: {geometry: "447x346#", processors: [:cropper_spp_one_third]}
  },
                    url: "http://www.studentpeaceprize.org/system/spp_articles/:attachment/:id_partition/:style/:filename",
                    path: ":rails_root/public/system/spp_articles/:attachment/:id_partition/:style/:filename"
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  respond_to :html, :xml
  # GET /articles
  # GET /articles.xml
  def index
    @articles = Article.visible.where(press_release: 0).sorted.limit(5)
    if I18n.locale == :en
      @articles.reject!{|x| x.title_en.to_s.strip.length == 0 }
    else
      @articles.reject!{|x| x.title_no.to_s.strip.length == 0 }
    end
  end
 
  # GET /articles/1
  # GET /articles/1.xml
  def show
    @article = Article.find(params[:id])

    @related = Article.visible.where(press_release: 0).sorted.limit(5)
    @related.reject!{|x| x == @article }

    if I18n.locale == :en
      @related.reject!{|x| x.title_en.to_s.strip.length == 0 }
    else
      @related.reject!{|x| x.title_no.to_s.strip.length == 0 }
    end
  end

  def all
    @articles = Article.visible.where(press_release: 0).sorted.paginate(:page => params[:page], :per_page => 5)
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper

  def youtube_movie(link, klass)
    render "shared/youtube", link: link, klass: klass
  end
  
  def format(str)
    set_correct_tags(str)
    reg = Regexp.new(/\[([\w ,:"]+)\]\(([A-Za-z0-9_:.=&+-?\/]+)\)/)
    str.gsub!(reg, "<a href=\"\\2\" target=\"_blank\">\\1</a>")
    str.gsub!(/##yt (\w+) yt##/, youtube_movie("\\1", "klasse"))

    bc = BlueCloth.new(str) 
    #str.gsub!(/([^>])\s*\r\n\r\n\s*([^<])/m, "\\1<br /><br />\\2")
    #str.gsub!(/([^>])\s*\r\n\s*([^<])/m, "\\1<br />\\2")
    #str



    text = bc.to_html
    #set_correct_tags(text)
    text
  end

  def set_correct_tags(text)
    while text.index('##pic') != nil
      t_start = text.index('##pic')
      t_end = text.index('pic##')
      reg = Regexp.new(/##pic (\d+) (\d+) pic##/)
      match = reg.match(text[t_start..t_end+4])
      img_id = match[1]
      img_type = match[2]
      url = article_image(img_id.to_i, img_type.to_i, false)
      text[t_start..t_end+4] = url
    end

    while text.index('#l#pic') != nil
      t_start = text.index('#l#pic')
      t_end = text.index('pic#l#')
      reg = Regexp.new(/#l#pic (\d+) (\d+) pic#l#/)
      match = reg.match(text[t_start..t_end+5])
      img_id = match[1]
      img_type = match[2]
      url = article_image(img_id.to_i, img_type.to_i, true)
      text[t_start..t_end+5] = url
    end
  end

  def article_image(picture_id, type, link)
    picture = Photo.find_by_id(picture_id)
    if picture
    style = case type.to_s
      when "1" then "photo_full"
      when "2" then "photo_one_third_left"
      when "3" then "photo_one_third_middle"
      when "4" then "photo_one_third_right"
    end

    img_text = picture.image_text_en
    pic_url = type == 1 ? picture.spp_full_article_picture.url : picture.spp_one_third_article_picture.url
    #Change on prod!

    if (link)
      url = "<a href=/assets/#{picture.original_picture.url}><div class=#{style}><img src =/assets/#{pic_url}  /><br /><i>#{picture.credits}</i><br /><i>#{picture.image_text_en}</i></div></a>"
    else
      url = "<div class=#{style}><img src =/assets/#{pic_url}  /><br /><i>#{picture.credits}</i><br /><i>#{picture.image_text_en}</i></div>"
    end
    else
    ""
    end
  end
end

app/views/articles/_article.html.erb
<div class="da-slide">
  <h2><%= use_english? ? article.title_en : article.title_no %></h2>
  <!--p><%= use_english? ? article.ingress_en : article.ingress_no %></p-->
  <%= link_to use_english? ? "Read more" : "Les mer", article_path(article), class: "da-link" %>
  <div class="da-img">
    <%= image_tag article.spp_article_image.url(:article) %>
  </div>
</div>

app/views/articles/all.html.erb
<%= content_for :meta do %>
  <meta property="og:title" content="All articles"/>
  <meta property="og:type" content="non_profit"/>
  <meta property="og:url" content="<%=(request.url).match(/([A-Za-z0-9:._\/]+)/)[1]%>"/>          
  <meta property="og:site_name" content="Student Peace Prize"/>
  <meta property="fb:app_id" content="132392463483362"/>
  <meta property="og:description" content="All articles"/>
<%end%>

<%= content_for :title do %>
  <% t('all_page_title') %>
<% end %>
<!--start: Wrapper-->
<div id="wrapper">

  <!--start: Container -->
  <div class="container">

    <hr>

    <!-- start: Row -->
    <div class="row">


<% @articles.each do |article| %>

<div id="article-header">
  <h1><%= link_to use_english? ? article.title_en : article.title_no, article_path(article.id) %></h1>
  <p><%= use_english? ? article.ingress_en : article.ingress_no %> </p>
</div>
<div id="article-metadata">
  <span class="byline">
    <em><%= t('.text') %>:</em> <%= article.byline %>
    <em><%= t('.photo') %>:</em> <%= article.image_text %>
    <em><%= t('.date') %>:</em> <%= article.created_at.strftime("%F") %>
  </span>
</div>
<%if @articles.last != article %>
<br />
<%end%>
<%end%>
<navbar-nav>
<div class="pagigation pagination-centered">
  <%= will_paginate @articles, :renderer => BootstrapPagination::Rails, :container => false %>
</div>
</navbar-nav>
</div>
</div>
</div>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= form_for(@article) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :title_en %><br />
    <%= f.text_field :title_en %>
  </p>
  <p>
    <%= f.label :title_no %><br />
    <%= f.text_field :title_no %>
  </p>
  <p>
    <%= f.label :ingress_en %><br />
    <%= f.text_area :ingress_en %>
  </p>
  <p>
    <%= f.label :ingress_no %><br />
    <%= f.text_area :ingress_no %>
  </p>
  <p>
    <%= f.label :body_en %><br />
    <%= f.text_area :body_en %>
  </p>
  <p>
    <%= f.label :body_no %><br />
    <%= f.text_area :body_no %>
  </p>
  <p>
    <%= f.label :press_release %><br />
    <%= f.check_box :press_release %>
  </p>
  <p>
    <%= f.label :deleted %><br />
    <%= f.check_box :deleted %>
  </p>
  <p>
    <%= f.label :visible %><br />
    <%= f.check_box :visible %>
  </p>
  <p>
    <%= f.label :main_article %> <br />
    <%= f.check_box :main_article %> <br />
  </p>
  <p>
    <%=link_to 'Edit Main Picture', {:controller => 'pictures', :action=> 'new', :tab => params[:tab], :article_id => @article.id}, {:popup => true}%>
  </p>
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<%= content_for :meta do %>
  <meta property="og:type" content="website">
  <meta property="og:image" content="http://www.studentpeaceprize.org/assets/logo-fredspris.png">
  <meta property="og:url" content="http://www.studentpeaceprize.org/">
  <meta property="og:title" content="The Student Peace Prize">
  <meta property="og:site_name" content="Student Peace Prize"/>
  <meta property="fb:app_id" content="132392463483362"/>
  <meta property="og:description" content="The Student Peace Prize is given out every other year on behalf of all students in Norway.">
<% end %>

<!-- start: Slider -->
<div class="slider-wrapper">

  <div id="da-slider" class="da-slider">

    <% @articles.each do |article| %>
      <%= render article %>
    <% end %>

    <nav class="da-arrows">
    <span class="da-arrows-prev"></span>
    <span class="da-arrows-next"></span>
    </nav>
  </div>

</div>
<!-- end: Slider -->

<!--start: Wrapper-->
<div id="wrapper">

  <!--start: Container -->
  <div class="container">
    <hr>
    <!--div class="hero-unit">
      <h3><%= t('.ceremony.header') %></h3>
      <h4><%= t('.ceremony.subhead') %></h4>
				<p>
					<%= t('.ceremony.paragraph') %>
				</p>
          <p><a href="http://www.youtube.com/watch?v=hAd0jVZOJ8s" class="btn btn-primary btn-large"><%= t('.ceremony.watch_now') %></a></p>
      		</div-->

    <!-- start: Row -->
    <div class="row">

      <!-- start: Icon Boxes -->
      <div class="icons-box-vert-container">

        <!-- start: Icon Box Start -->
        <div class="span4">
          <div class="icons-box-vert">
            <i class="ico-cup ico-white circle-color-full"></i>
            <div class="icons-box-vert-info">
              <h3><%= link_to t('.about_paragraph_left_title'), page_path(16, tab: "about") %></h3>
              <p><%= t('.about_paragraph_left_body') %></p>
            </div>
            <div class="clear"></div>
          </div>
        </div>
        <!-- end: Icon Box-->

        <!-- start: Icon Box Start -->
        <div class="span4">
          <div class="icons-box-vert">
            <i class="ico-road ico-white circle-color-full"></i>
            <div class="icons-box-vert-info">
              <h3><%= link_to t('.about_paragraph_center_title'), page_path(20, tab: "about") %></h3>
              <p><%= t('.about_paragraph_center_body') %></p>
            </div>
            <div class="clear"></div>
          </div>
        </div>
        <!-- end: Icon Box -->

        <!-- start: Icon Box Start -->
        <div class="span4">
          <div class="icons-box-vert">
            <i class="ico-leaf  ico-white circle-color-full"></i>
            <div class="icons-box-vert-info">
              <h3><%= link_to t('.about_paragraph_right_title'), page_path(37, tab: "about") %></h3>
              <p><%= t('.about_paragraph_right_body') %></p>
            </div>
            <div class="clear"></div>
          </div>
        </div>
        <!-- end: Icon Box -->

      </div>
      <!-- end: Icon Boxes -->
      <div class="clear"></div>
    </div>
    <!-- end: Row -->
    <hr>
  </div>
  <!--end: Container-->

</div>
<!-- end: Wrapper  -->	

app/views/articles/new.html.erb
<h1><%= t('new_article.title') %></h1>

<%= form_for(@article, :tab=>params[:tab]) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :title_en %><br />
    <%= f.text_field :title_en %>
  </p>
  <p>
    <%= f.label :title_no %><br />
    <%= f.text_field :title_no %>
  </p>
  <p>
    <%= f.label :ingress_en %><br />
    <%= f.text_area :ingress_en %>
  </p>
  <p>
    <%= f.label :ingress_no %><br />
    <%= f.text_area :ingress_no %>
  </p>
  <p>
    <%= f.label :body_en %><br />
    <%= f.text_area :body_en %>
  </p>
  <p>
    <%= f.label :body_no %><br />
    <%= f.text_area :body_no %>
  </p>
  <p>
    <%= f.label :press_release %><br />
    <%= f.check_box :press_release %>
  </p>
  <p>
    <%= f.label :deleted %><br />
    <%= f.check_box :deleted %>
  </p>
  <p>
    <%= f.label :visible %><br />
    <%= f.check_box :visible %>
  </p>
  <p>
    <%= f.label :main_article %> <br />
    <%= f.check_box :main_article %>
  </p>
  <p>
    <%= f.submit t(create) %>
  </p>
<% end %>
<%= link_to t(back), articles_path %>

app/views/articles/show.html.erb
<%= content_for :meta do %>
  <meta property="og:title" content="<%=@article.title_en %>."/>
  <meta property="og:type" content="non_profit"/>
  <meta property="og:image" content="http://www.studentpeaceprize.org/<%= @article.spp_article_image.url(:front_small) %>"/>
  <meta property="og:url" content="<%=(request.url).match(/([A-Za-z0-9:._\/]+)/)[1]%>"/>          
  <meta property="og:site_name" content="Student Peace Prize"/>
  <meta property="fb:app_id" content="132392463483362"/>
  <meta property="og:description" content="<%=@article.ingress_en %>"/>
<%end%>

<%= content_for :title do %>
  <%= use_english? ? @article.title_en : @article.title_no + " -" %>
<% end %>
<!-- start: Page Title -->
<div id="page-title">

  <div id="page-title-inner">

    <!-- start: Container -->
    <div class="container">

      <h2><%= use_english? ? @article.title_en : @article.title_no %></h2>

    </div>
    <!-- end: Container  -->

  </div>	

</div>
<!-- end: Page Title -->

<!--start: Wrapper-->
<div id="wrapper">

  <!--start: Container -->
  <div class="container">

    <!--start: Row -->
    <div class="row">

      <div class="col-md-6">

        <!-- start: Post -->
        <div class="post post-page">
          <div class="post-img picture">
            <%if @article.youtube_link? %>
              <%= youtube_movie @article.youtube_link, :show_youtube %>
            <%else%>
              <%= image_tag @article.spp_article_image.url(:front_large) %>
            <%end%>
          </div>
          <div class="post-content">
            <div class="post-ingress">
              <%= use_english? ? @article.ingress_en : @article.ingress_no %>
            </div>
            <div class="post-description">
              <%=raw format(use_english? ? @article.body_en : @article.body_no )%>
            </div>

            <div class="post-meta">
              <i class="mini-ico-calendar"></i><em><%= t('.date') %>:</em> <%= @article.created_at.strftime("%F") %>
              <i class="mini-ico-user"></i><em><%= t('.text') %>:</em> <%= @article.byline %>
              <i class="mini-ico-image"></i><em><%= t('.photo') %>:</em> <%= @article.image_text %>
            </div> </div>
          <%if @article.got_comments %>
            <div class="fb-comments" data-href="<%=request.url %>" data-num-posts="5" data-width="620"></div>
          <%end%>
        </div>
        <!-- end: Post -->
      </div>
      <!-- end: span9 -->
<!-- span3 -->
<div class="col-md-4 col-md-offset-2">
  <% cache(:action => "show", :action_suffix => @article.id.to_s ) do %>

    <div class="title"><h3><%= t('related_articles') %></h3></div>
    <% @related.each do |page| %>
      <div class="portfolio-item nature people isotope-item" >
        <div class="picture">
          <%= link_to article_path(page) do %>
            <%if page.youtube_link? %>
            <%else%>
              <%= image_tag page.spp_article_image.url(:front_small) %>
            <%end%>
            <div class="image-overlay-link" style="opacity: 0; display: block; "></div>
          <%end%>
          <div class="item-description alt">
            <h5><a href="project.html"><%= use_english? ? page.title_en : page.title_no %></a></h5>
            <p>
            <%= raw format use_english? ? page.ingress_en : page.ingress_no %>
            </p>
          </div>
          <div class="post-meta"><span><i class="mini-ico-calendar"></i><%= page.updated_at.strftime("%-d %B %Y") %></span></div>
        </div>	
      </div>
    <% end %>
    <ul class="links-list-alt">
      <li><%= link_to t('menu_articles'), all_articles_path %></li>
    </ul>
  <% end %>
</div>
      <!-- end: span3 -->


    </div>
    <!-- end: row -->      
  </div>
  <!--end: Container-->

</div>
<!-- end: Wrapper  -->		